apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth-app
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth
          image: ghcr.io/giveaway-mongo/auth:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: auth-configmap
          ports:
            - containerPort: 50051
              name: auth-port
