apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8080
      targetPort: auth-port
      name: auth-service-port
      protocol: TCP