name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start test
      run: git submodule init |
        && git submodule update --merge --recursive --remote |
        && docker build -f Dockerfile.test -t app . |
        && docker-compose -f docker-compose.test.yaml run app 
      
