name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start test
      run: docker build -f Dockerfile.test -t app . && docker-compose -f docker-compose.test.yaml run app
      
